<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="manageprojects.aspx.cs" Inherits="write_manageprojects" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <!-- This page gives the user an overview over all the projects in the database, and allows them to view data about them/edit them -->
    <asp:PlaceHolder ID="PlaceHolder1" runat="server"></asp:PlaceHolder>

    <div class="pageHeader">
        <asp:Label ID="manageProjectsHeaderLabel" runat="server">Manage Projects</asp:Label>
    </div>

    <div class="contentCenterer">
        <p>Select or search for a project below to manage.</p>
    </div>

    <div class="contentCenterer">
        <!-- The amount of projects can be large, so the user can search for a particular one -->
        <asp:TextBox ID="TextBox1" CssClass="searchBox" placeholder="Project ID..." runat="server" AutoPostBack="true" OnTextChanged="SearchProjectOnEvent" onfocus="this.select();"></asp:TextBox>

        <!-- An autocompleteextender helps the user find the desired project -->
        <cc1:AutoCompleteExtender
            ServiceMethod="GetCompletionList"
            MinimumPrefixLength="2"
            CompletionInterval="100"
            EnableCaching="false"
            CompletionSetCount="10"
            TargetControlID="TextBox1"
            ID="AutoCompleteExtender1"
            runat="server"
            FirstRowSelected="false">
        </cc1:AutoCompleteExtender>

        <asp:Button ID="Button1" runat="server" CssClass="searchButton" OnClick="SearchButtonClicked" Text="Search" />
    </div>

    <!-- We add some columns with buttons in addition to the autogenerated columns from the query. This allows us to do more -->
    <div class="contentCenterer">
        <asp:GridView ID="GridView1" runat="server" ShowHeaderWhenEmpty="True" EmptyDataText="No projects found!" AllowPaging="true" PageSize="12" OnPageIndexChanging="OnPageIndexChanging">
            <PagerStyle HorizontalAlign="Right" CssClass="GridPager" />
            <Columns>
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:Button ID="viewDataButton" runat="server" OnClick="ViewDataForSelectedRow" Text="View data" />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField>
                    <ItemTemplate>
                        <asp:Button ID="editButton" runat="server" OnClick="EditSelectedRow" Text="Edit project" />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </div>

</asp:Content>
